use [Movies]
insert into [Directors]([FirstName],[LastName],[Nationality],[Birth])
		values(N'Майкл', N'Бэй', N'Американец', N'19700425')
insert into [Directors]([FirstName],[LastName],[Nationality],[Birth])
		values(N'Владос', N'Папландос', N'Русский', N'19730726')
insert into [Directors]([FirstName],[LastName],[Nationality],[Birth])
		values(N'Никитос', N'Выкрунтос', N'Белорус', N'19821105')
insert into [Directors]([FirstName],[LastName],[Nationality],[Birth])
		values(N'Тарас', N'Шевченко', N'Украинец', N'19950212')
insert into [Directors]([FirstName],[LastName],[Nationality],[Birth])
		values(N'Хидэо', N'Кодзима', N'Казах', N'10830716')
go
insert into [Genres]([GenreName])
		values(N'Хоррор')
insert into [Genres]([GenreName])
		values(N'Боевик')
insert into [Genres]([GenreName])
		values(N'Драма')
insert into [Genres]([GenreName])
		values(N'Комедия')
insert into [Genres]([GenreName])
		values(N'Детектив')
go
insert into [Movies]([DirectorID],[Title],[ReleaseYear],[Rating],[Plot],[MovieLength])
		values(1,N'Трансформеры',N'2020', 8.2, N'ГИГАНТСКИЕ МАТЬ ЕГО РОБОТЫ БЬЮТ ДРУГ ДРУГА ПО ЛИЦУ, ЧТО МОЖЕТ БЫТЬ ЛУЧШЕ?', 1.43)
insert into [Movies]([DirectorID],[Title],[ReleaseYear],[Rating],[Plot],[MovieLength])
		values(1,N'Кровью и потом',N'2020', 9.3, N'Не помню что там было, но друзья сказали класный фильм', 1.34)
insert into [Movies]([DirectorID],[Title],[ReleaseYear],[Rating],[Plot],[MovieLength])
		values(2,N'Приключения Владоса',N'2019', 8.5, N'История жизни Владоса', 2.05)
insert into [Movies]([DirectorID],[Title],[ReleaseYear],[Rating],[Plot],[MovieLength])
		values(2,N'Приключения Папландоса',N'2020', 8.5, N'История жизни Владоса(Ремейк)', 1.50)
insert into [Movies]([DirectorID],[Title],[ReleaseYear],[Rating],[Plot],[MovieLength])
		values(3,N'Никитос против Владоса',N'2019', 6.7, N'История ненависти Никитоса к Владосу', 1.56)
insert into [Movies]([DirectorID],[Title],[ReleaseYear],[Rating],[Plot],[MovieLength])
		values(3,N'Никитос против Папландоса',N'2020', 6.8, N'История ненависти Никитоса к Владосу(Ремейк)', 1.48)
insert into [Movies]([DirectorID],[Title],[ReleaseYear],[Rating],[Plot],[MovieLength])
		values(4,N'История каторги',N'2012', 9.3, N'Жизнь в каторге', 1.22)
insert into [Movies]([DirectorID],[Title],[ReleaseYear],[Rating],[Plot],[MovieLength])
		values(4,N'История после каторги',N'2014', 9.2, N'Жизнь после каторги', 1.32)
insert into [Movies]([DirectorID],[Title],[ReleaseYear],[Rating],[Plot],[MovieLength])
		values(5,N'Death Stranding',N'2018', 9.9, N'История о работнике Glovo', 1.40)
insert into [Movies]([DirectorID],[Title],[ReleaseYear],[Rating],[Plot],[MovieLength])
		values(5,N'Metal Gear Solid',N'2005', 9.9, N'Одноглазый мужик супер-солдат', 1.53)
go

insert into [MovieGenres]([MovieID], [GenreID])
		values(1,1)
insert into [MovieGenres]([MovieID], [GenreID])
		values(2,1)
insert into [MovieGenres]([MovieID], [GenreID])
		values(3,2)
insert into [MovieGenres]([MovieID], [GenreID])
		values(4,2)
insert into [MovieGenres]([MovieID], [GenreID])
		values(5,3)
go
insert into [MovieGenres]([MovieID], [GenreID])
		values(6,3)
insert into [MovieGenres]([MovieID], [GenreID])
		values(7,4)
insert into [MovieGenres]([MovieID], [GenreID])
		values(8,4)
insert into [MovieGenres]([MovieID], [GenreID])
		values(9,5)
insert into [MovieGenres]([MovieID], [GenreID])
		values(10,5)
go

insert into [Actors]([FirstName],[LastName],[Nationality],[Birth])
		values(N'Майкл', N'Бэй', N'Американец', N'19700425')
insert into [Actors]([FirstName],[LastName],[Nationality],[Birth])
		values(N'Владос', N'Папландос', N'Русский', N'19730726')
insert into [Actors]([FirstName],[LastName],[Nationality],[Birth])
		values(N'Никитос', N'Выкрунтос', N'Белорус', N'19821105')
insert into [Actors]([FirstName],[LastName],[Nationality],[Birth])
		values(N'Тарас', N'Шевченко', N'Украинец', N'19950212')
insert into [Actors]([FirstName],[LastName],[Nationality],[Birth])
		values(N'Хидэо', N'Кодзима', N'Казах', N'10830716')
go

insert into [MovieActor]([MovieID], [ActorID])
		values(1,1)
insert into [MovieActor]([MovieID], [ActorID])
		values(2,1)
insert into [MovieActor]([MovieID], [ActorID])
		values(3,2)
insert into [MovieActor]([MovieID], [ActorID])
		values(4,2)
insert into [MovieActor]([MovieID], [ActorID])
		values(5,3)
go
insert into [MovieActor]([MovieID], [ActorID])
		values(6,3)
insert into [MovieActor]([MovieID], [ActorID])
		values(7,4)
insert into [MovieActor]([MovieID], [ActorID])
		values(8,4)
insert into [MovieActor]([MovieID], [ActorID])
		values(9,5)
insert into [MovieActor]([MovieID], [ActorID])
		values(10,5)
go